### ISSUE TITLE
import compareVersions from 'compare-versions'; not working 

### ISSUE THREAD

**Issue by imranwaheed-10p** [omichelsen/compare-versions#44] opened 2021-07-01 11:06 UTC
instead it is working like that in nest js typescript 

import * as compareVersions from 'compare-versions';

**Comment by omichelsen** [comment] 2021-10-24 16:23
It sounds like you have to enable [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) in your tsconfig?

**Comment by the-noob** [comment] 2021-11-01 10:15
Just got to upgrading this and hit the same error

```
import compareVersions from "compare-versions";
       ^^^^^^^^^^^^^^^
SyntaxError: The requested module 'compare-versions' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

The entire package is marked as module ( `  "type": "module",`).
Tried changing to a named import, no luck.
```
import { compareVersions } from "compare-versions";
         ^^^^^^^^^^^^^^^
SyntaxError: The requested module 'compare-versions' does not provide an export named 'compareVersions'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
 ```

PS: not using TS

**Comment by revelt** [comment] 2021-11-01 13:56
I'm getting the same, using TS setup, `SyntaxError: The requested module 'compare-versions' does not provide an export named 'default'`. It's blocking my package `json-comb-core` from building at all.

@omichelsen I can help to raise a PR to improve the setup, to produce UMD and ESM builds using Rollup/esbuild and generate type definitions automatically. Also, strictly looking at the `package.json`, `main` and `module` could be removed, then the wiring could be like this:

```
"type": "module",
"exports": {
  "script": "./dist/compare-versions.umd.js",
  "default": "./dist/compare-versions.esm.js"
},
"types": "types/index.d.ts",
```

If we could rewrite the sources in TS as well and let Rollup generate the types, that would be ideal — you would have guaranteed spot-on types because they would be machine-generated. At least that's what I use in my packages. Anyway, be it source in JS or TS, I believe Rollup would help to avoid the hardcoded UMD boilerplate in the source. I suspect the UMD boilerplate part.

**Comment by omichelsen** [comment] 2021-11-01 14:29
Could you please post your tsconfig, and I will try and fix. I’d like to avoid adding tons of build dependencies for such a small package, which I why I didn’t go with with TS source even though I love TS.

Nothing should have changed in v4 regarding the UMD source, and the new added module field in package.json should mean that your bundler should pick up the new ESM version instead of the UMD. That’s why I’d be interested in your setup to reproduce.

**Comment by revelt** [comment] 2021-11-01 16:23
@omichelsen Sure! The monorepo is https://github.com/codsen/codsen
The package in question is json-comb-core — https://github.com/codsen/codsen/blob/main/packages/json-comb-core/package.json - it's using `compare-versions` of "^3.6.0", which I tried to bump locally to v4.

I'm on ESModules myself btw.

To run the tests:

1. git clone the https://github.com/codsen/codsen
2. `npm run bootstrap` (because it's Lerna monorepo)
3. cd packages/json-comb-core
4. `npm run test` — should work fine, because `compare-versions` is "^3.6.0" there
5. manually bump the `compare-versions` in package.json of json-comb-core to v4
6. in monorepo root, `npm run bootstrap` again
7. cd packages/json-comb-core
8. `npm run test` — now it will fail

**Comment by revelt** [comment] 2021-11-01 16:41
I'm reading the new Node `exports` [documentation](https://nodejs.org/api/modules.html), it does say that `main` will be ignored if `exports` exist. But there is not any in our case, so I have a hypothesis that it falls back to `main`, and in our case it's umd and default export issue surfaces up — even though, `module` is pointing to a healthy `index.mjs`.

I just went to my node_modules, to `compare-versions` package.json, and replaced `main` and `modules` lines with `exports`:

```json
{
  "name": "compare-versions",
  "version": "4.0.0",
  "description": "Compare semver version strings to find greater, equal or lesser.",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/omichelsen/compare-versions.git"
  },
  "author": "Ole Michelsen",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/omichelsen/compare-versions/issues"
  },
  "homepage": "https://github.com/omichelsen/compare-versions#readme",
  "keywords": [
    "semver",
    "version",
    "compare",
    "browser",
    "node"
  ],
  "scripts": {
    "test": "c8 mocha"
  },
  "type": "module",
  "exports": {
    "script": "./index.js",
    "default": "./index.mjs"
  },
  "types": "index.d.ts",
  "files": [
    "index.js",
    "index.mjs",
    "index.d.ts"
  ],
  "devDependencies": {
    "c8": "^7.10.0",
    "mocha": "^9.0.0"
  }
}
```

all worked again! That supports the hypothesis, right? It's the Node resolving the entry point to the wrong file.

**Comment by omichelsen** [comment] 2021-11-02 00:25
It seems like the `"type": "module"` line is messing up your config. If I remove just that it works. I have released this as v4.0.1, it seems like this setting causes problems with some build systems, and I think we can do without.

**Comment by revelt** [comment] 2021-11-02 09:01
I agree with your feeling on build systems, actually, the main competitor of this very package, `semver-compare` by substack is still on CJS and doesn't have UMD. Six and half million downloads weekly.

Considering our v4.01, `type: module` sets the package to be classified as the native ES Modules-type. Sindre Sorhus wrote about it [here](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77) and [here](https://github.com/sindresorhus/meta/discussions/15). It's part of migration to native ES modules setup. It seems that during v4 we nearly completed the whole migration, only `exports` field was missing. Now, when we removed `type: modules`, we set the package to be not native ESM — which is fine — just then, "wiring" has to be done old ways, using `module` and `main`. 

Personally, in this situation, I'd consider restoring `type: modules` and wiring up `exports` to link `script` to UMD and `default` to `.mjs` file. Also, each time we add or remove `type: modules`, if approaching it strictly, it's a breaking/major semver change. That's another consideration.

**Comment by omichelsen** [comment] 2021-11-02 14:18
Good points. ~~I couldn't find where it says exports is a new standard though. It sounds like it's a hack to get old CJS modules to work, why I was hesitant to add it. I'll check out the links you sent.~~ Edit: it's [described well here](https://nodejs.org/api/packages.html#conditional-exports).

I know of semver-compare but it doesn't implement the full spec, pre-releases aren't handled etc, so guess people just don't need that.

**Comment by omichelsen** [comment] 2021-11-02 19:08
I made the [module](https://github.com/omichelsen/compare-versions/compare/module?expand=1) branch if you'd like to try out how that works.

**Comment by the-noob** [comment] 2021-11-03 10:01
4.0.1 fixed it for me

**Comment by omichelsen** [comment] 2021-11-12 18:35
Will probably switch this library to 100% module at some point, but for now it seems having both CJS and ESM works for people so I'll close this.

**Closed as completed by omichelsen** 2021-11-12 18:35 UTC
Labels: question
